channels:
- conda-forge
dependencies:
- python=3.12.7
- pip<=25.1
- pip:
  - mlflow==2.19.0
  - cloudpickle==3.1.1
  - numpy==2.0.1
  - pandas==2.2.3
  - psutil==5.9.0
  - scikit-learn==1.6.1
  - scipy==1.15.2
  - seaborn==0.13.2
  - dagshub==0.5.9
name: mlflow-env
