name: Workflow-CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  X_TRAIN_URL: "MLProject/weather_preprocessing/X_train.csv"
  X_TEST_URL: "MLProject/weather_preprocessing/X_test.csv"
  Y_TRAIN_URL: "MLProject/weather_preprocessing/y_train.csv"
  Y_TEST_URL: "MLProject/weather_preprocessing/y_test.csv"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Run actions/checkout@4
        uses: actions/checkout@v4

      - name: Setup Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.7
      
      - name: Check env
        run: |
          echo $X_TRAIN_URL
          echo $X_TEST_URL
          echo $Y_TRAIN_URL
          echo $Y_TEST_URL
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas matplotlib scikit-learn mlflow dagshub
      
      - name: Run mlflow project
        run: |
          mlflow run MLProject --env-manager=local
      
      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"
      
      - name: Install Python dependencies for upload to Google Drive
        run: |
          pip install --upgrade google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client
      
      - name: Upload to Google Drive
        env:
          GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}  # Mengambil kredensial dari GitHub Secrets
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}  # Mengambil kredensial dari GitHub Secrets
        run: |
          python MLProject/upload_to_gdrive.py
      
      - name: Build Docker Model
        run: |
          mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "workflow-ci"
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Tag Docker Image
        run: |
          docker tag workflow-ci ${{ secrets.DOCKER_HUB_USERNAME }}/workflow-ci:latest
      
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/workflow-ci:latest
